""" Author: Ahmad Alzeitoun, The University of Bonn
    Date created: 02/2022
    Status: Production
"""

import requests
from requests.structures import CaseInsensitiveDict

url = "http://127.0.0.1:8000/answer/" #This URL should be the same URL that is generated by FasAPI.

headers = CaseInsensitiveDict()
headers["accept"] = "application/json"
headers["Content-Type"] = "application/json"

data = '''{
            "question_txt": "What is your name?",
            "topic_entity_id": "Q3035"
        }'''
resp = requests.post(url, headers=headers, data=data)
print(resp.json())
